### ISSUE TITLE
Release zip file

### ISSUE THREAD

**Issue by Mte90** [SiD3W4y/GhidraGBA#3]
It is possible to release a package ready to use instead to install gradle? 
It is a big tool and just install to generate a tiny zip is kind of useless.

**Comment by HDR** [comment]
[ghidra_9.1.2_PUBLIC_20200610_GhidraGBA-master.zip](https://github.com/SiD3W4y/GhidraGBA/files/4760406/ghidra_9.1.2_PUBLIC_20200610_GhidraGBA-master.zip)

**Comment by SiD3W4y** [comment]
Done for 9.2
